# Generated by Django 3.0.2 on 2020-10-07 22:21

from django.db import migrations
import multiselectfield.db.fields


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0020_auto_20200814_1249'),
    ]

    operations = [
        migrations.AlterField(
            model_name='anime',
            name='platforms',
            field=multiselectfield.db.fields.MultiSelectField(blank=True, choices=[(5, 'CDA'), (3, 'AMAZONPRIME'), (2, 'NETFLIX'), (4, 'YOUTUBE'), (1, 'HBO')], max_length=9, null=True),
        ),
        migrations.AlterField(
            model_name='movie',
            name='platforms',
            field=multiselectfield.db.fields.MultiSelectField(blank=True, choices=[(5, 'CDA'), (3, 'AMAZONPRIME'), (2, 'NETFLIX'), (4, 'YOUTUBE'), (1, 'HBO')], max_length=9, null=True),
        ),
        migrations.AlterField(
            model_name='serial',
            name='platforms',
            field=multiselectfield.db.fields.MultiSelectField(blank=True, choices=[(5, 'CDA'), (3, 'AMAZONPRIME'), (2, 'NETFLIX'), (4, 'YOUTUBE'), (1, 'HBO')], max_length=9, null=True),
        ),
    ]
