# Generated by Django 3.0.2 on 2020-10-15 22:32

from django.db import migrations, models
import django.db.models.deletion
import multiselectfield.db.fields


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0022_auto_20201014_2354'),
    ]

    operations = [
        migrations.AlterField(
            model_name='anime',
            name='genre',
            field=models.PositiveSmallIntegerField(choices=[(3, 'Sci-fi'), (0, 'Inne'), (1, 'Horror'), (2, 'Komedia')], default=0),
        ),
        migrations.AlterField(
            model_name='anime',
            name='platforms',
            field=multiselectfield.db.fields.MultiSelectField(blank=True, choices=[(1, 'HBO'), (3, 'AMAZONPRIME'), (4, 'YOUTUBE'), (2, 'NETFLIX'), (5, 'CDA')], max_length=9, null=True),
        ),
        migrations.AlterField(
            model_name='movie',
            name='genre',
            field=models.PositiveSmallIntegerField(choices=[(3, 'Sci-fi'), (0, 'Inne'), (1, 'Horror'), (2, 'Komedia')], default=0),
        ),
        migrations.AlterField(
            model_name='movie',
            name='platforms',
            field=multiselectfield.db.fields.MultiSelectField(blank=True, choices=[(1, 'HBO'), (3, 'AMAZONPRIME'), (4, 'YOUTUBE'), (2, 'NETFLIX'), (5, 'CDA')], max_length=9, null=True),
        ),
        migrations.AlterField(
            model_name='serial',
            name='genre',
            field=models.PositiveSmallIntegerField(choices=[(3, 'Sci-fi'), (0, 'Inne'), (1, 'Horror'), (2, 'Komedia')], default=0),
        ),
        migrations.AlterField(
            model_name='serial',
            name='platforms',
            field=multiselectfield.db.fields.MultiSelectField(blank=True, choices=[(1, 'HBO'), (3, 'AMAZONPRIME'), (4, 'YOUTUBE'), (2, 'NETFLIX'), (5, 'CDA')], max_length=9, null=True),
        ),
        migrations.CreateModel(
            name='MovieRating',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('review', models.TextField(default='')),
                ('rating', models.PositiveSmallIntegerField(default=5)),
                ('movie', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main.Movie')),
            ],
        ),
    ]
