# Generated by Django 3.0.2 on 2020-10-17 00:08

from django.db import migrations, models
import multiselectfield.db.fields


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0024_auto_20201016_0011'),
    ]

    operations = [
        migrations.CreateModel(
            name='Actor',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=32)),
                ('last_name', models.CharField(max_length=32)),
            ],
        ),
        migrations.AlterField(
            model_name='anime',
            name='genre',
            field=models.PositiveSmallIntegerField(choices=[(2, 'Komedia'), (3, 'Sci-fi'), (0, 'Inne'), (1, 'Horror')], default=0),
        ),
        migrations.AlterField(
            model_name='anime',
            name='platforms',
            field=multiselectfield.db.fields.MultiSelectField(blank=True, choices=[(3, 'AMAZONPRIME'), (1, 'HBO'), (4, 'YOUTUBE'), (5, 'CDA'), (2, 'NETFLIX')], max_length=9, null=True),
        ),
        migrations.AlterField(
            model_name='movie',
            name='genre',
            field=models.PositiveSmallIntegerField(choices=[(2, 'Komedia'), (3, 'Sci-fi'), (0, 'Inne'), (1, 'Horror')], default=0),
        ),
        migrations.AlterField(
            model_name='movie',
            name='platforms',
            field=multiselectfield.db.fields.MultiSelectField(blank=True, choices=[(3, 'AMAZONPRIME'), (1, 'HBO'), (4, 'YOUTUBE'), (5, 'CDA'), (2, 'NETFLIX')], max_length=9, null=True),
        ),
        migrations.AlterField(
            model_name='serial',
            name='genre',
            field=models.PositiveSmallIntegerField(choices=[(2, 'Komedia'), (3, 'Sci-fi'), (0, 'Inne'), (1, 'Horror')], default=0),
        ),
        migrations.AlterField(
            model_name='serial',
            name='platforms',
            field=multiselectfield.db.fields.MultiSelectField(blank=True, choices=[(3, 'AMAZONPRIME'), (1, 'HBO'), (4, 'YOUTUBE'), (5, 'CDA'), (2, 'NETFLIX')], max_length=9, null=True),
        ),
        migrations.AddField(
            model_name='movie',
            name='actors',
            field=models.ManyToManyField(blank=True, to='main.Actor'),
        ),
    ]
