# Generated by Django 3.0.2 on 2020-10-17 01:01

from django.db import migrations, models
import multiselectfield.db.fields


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0025_auto_20201017_0008'),
    ]

    operations = [
        migrations.AddField(
            model_name='anime',
            name='actors',
            field=models.ManyToManyField(blank=True, to='main.Actor'),
        ),
        migrations.AddField(
            model_name='serial',
            name='actors',
            field=models.ManyToManyField(blank=True, to='main.Actor'),
        ),
        migrations.AlterField(
            model_name='anime',
            name='genre',
            field=models.PositiveSmallIntegerField(choices=[(3, 'Sci-fi'), (2, 'Komedia'), (0, 'Inne'), (1, 'Horror')], default=0),
        ),
        migrations.AlterField(
            model_name='anime',
            name='platforms',
            field=multiselectfield.db.fields.MultiSelectField(blank=True, choices=[(5, 'CDA'), (4, 'YOUTUBE'), (3, 'AMAZONPRIME'), (2, 'NETFLIX'), (1, 'HBO')], max_length=9, null=True),
        ),
        migrations.AlterField(
            model_name='movie',
            name='genre',
            field=models.PositiveSmallIntegerField(choices=[(3, 'Sci-fi'), (2, 'Komedia'), (0, 'Inne'), (1, 'Horror')], default=0),
        ),
        migrations.AlterField(
            model_name='movie',
            name='platforms',
            field=multiselectfield.db.fields.MultiSelectField(blank=True, choices=[(5, 'CDA'), (4, 'YOUTUBE'), (3, 'AMAZONPRIME'), (2, 'NETFLIX'), (1, 'HBO')], max_length=9, null=True),
        ),
        migrations.AlterField(
            model_name='serial',
            name='genre',
            field=models.PositiveSmallIntegerField(choices=[(3, 'Sci-fi'), (2, 'Komedia'), (0, 'Inne'), (1, 'Horror')], default=0),
        ),
        migrations.AlterField(
            model_name='serial',
            name='platforms',
            field=multiselectfield.db.fields.MultiSelectField(blank=True, choices=[(5, 'CDA'), (4, 'YOUTUBE'), (3, 'AMAZONPRIME'), (2, 'NETFLIX'), (1, 'HBO')], max_length=9, null=True),
        ),
    ]
