# Generated by Django 3.0.2 on 2020-10-18 22:47

from django.db import migrations, models
import multiselectfield.db.fields


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0026_auto_20201017_0101'),
    ]

    operations = [
        migrations.AlterField(
            model_name='anime',
            name='genre',
            field=models.PositiveSmallIntegerField(choices=[(3, 'Sci-fi'), (2, 'Komedia'), (1, 'Horror'), (0, 'Inne')], default=0),
        ),
        migrations.AlterField(
            model_name='anime',
            name='platforms',
            field=multiselectfield.db.fields.MultiSelectField(blank=True, choices=[(2, 'NETFLIX'), (5, 'CDA'), (1, 'HBO'), (4, 'YOUTUBE'), (3, 'AMAZONPRIME')], max_length=9, null=True),
        ),
        migrations.AlterField(
            model_name='movie',
            name='genre',
            field=models.PositiveSmallIntegerField(choices=[(3, 'Sci-fi'), (2, 'Komedia'), (1, 'Horror'), (0, 'Inne')], default=0),
        ),
        migrations.AlterField(
            model_name='movie',
            name='platforms',
            field=multiselectfield.db.fields.MultiSelectField(blank=True, choices=[(2, 'NETFLIX'), (5, 'CDA'), (1, 'HBO'), (4, 'YOUTUBE'), (3, 'AMAZONPRIME')], max_length=9, null=True),
        ),
        migrations.AlterField(
            model_name='serial',
            name='genre',
            field=models.PositiveSmallIntegerField(choices=[(3, 'Sci-fi'), (2, 'Komedia'), (1, 'Horror'), (0, 'Inne')], default=0),
        ),
        migrations.AlterField(
            model_name='serial',
            name='platforms',
            field=multiselectfield.db.fields.MultiSelectField(blank=True, choices=[(2, 'NETFLIX'), (5, 'CDA'), (1, 'HBO'), (4, 'YOUTUBE'), (3, 'AMAZONPRIME')], max_length=9, null=True),
        ),
    ]
