# Generated by Django 3.0.2 on 2020-10-21 18:49

from django.db import migrations, models
import multiselectfield.db.fields


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0028_auto_20201019_2057'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='actor',
            name='date_of_birth',
        ),
        migrations.AddField(
            model_name='actor',
            name='birth_date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='actor',
            name='image',
            field=models.ImageField(blank=True, default='video-default.jpg', null=True, upload_to='media/'),
        ),
        migrations.AlterField(
            model_name='actor',
            name='rating',
            field=models.IntegerField(blank=True, choices=[(0, 0), (1, 1), (2, 2), (3, 3), (4, 4), (5, 5), (6, 6), (7, 7), (8, 8), (9, 9), (10, 10)]),
        ),
        migrations.AlterField(
            model_name='anime',
            name='genre',
            field=models.PositiveSmallIntegerField(choices=[(2, 'Komedia'), (3, 'Sci-fi'), (0, 'Inne'), (1, 'Horror')], default=0),
        ),
        migrations.AlterField(
            model_name='anime',
            name='platforms',
            field=multiselectfield.db.fields.MultiSelectField(blank=True, choices=[(2, 'NETFLIX'), (1, 'HBO'), (5, 'CDA'), (4, 'YOUTUBE'), (3, 'AMAZONPRIME')], max_length=9, null=True),
        ),
        migrations.AlterField(
            model_name='movie',
            name='genre',
            field=models.PositiveSmallIntegerField(choices=[(2, 'Komedia'), (3, 'Sci-fi'), (0, 'Inne'), (1, 'Horror')], default=0),
        ),
        migrations.AlterField(
            model_name='movie',
            name='platforms',
            field=multiselectfield.db.fields.MultiSelectField(blank=True, choices=[(2, 'NETFLIX'), (1, 'HBO'), (5, 'CDA'), (4, 'YOUTUBE'), (3, 'AMAZONPRIME')], max_length=9, null=True),
        ),
        migrations.AlterField(
            model_name='serial',
            name='genre',
            field=models.PositiveSmallIntegerField(choices=[(2, 'Komedia'), (3, 'Sci-fi'), (0, 'Inne'), (1, 'Horror')], default=0),
        ),
        migrations.AlterField(
            model_name='serial',
            name='platforms',
            field=multiselectfield.db.fields.MultiSelectField(blank=True, choices=[(2, 'NETFLIX'), (1, 'HBO'), (5, 'CDA'), (4, 'YOUTUBE'), (3, 'AMAZONPRIME')], max_length=9, null=True),
        ),
    ]
