# Generated by Django 3.0.2 on 2020-10-21 18:58

from django.db import migrations, models
import multiselectfield.db.fields


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0029_auto_20201021_1849'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='actor',
            name='birth_date',
        ),
        migrations.AddField(
            model_name='actor',
            name='year_of_birth',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='anime',
            name='genre',
            field=models.PositiveSmallIntegerField(choices=[(0, 'Inne'), (3, 'Sci-fi'), (2, 'Komedia'), (1, 'Horror')], default=0),
        ),
        migrations.AlterField(
            model_name='anime',
            name='platforms',
            field=multiselectfield.db.fields.MultiSelectField(blank=True, choices=[(2, 'NETFLIX'), (1, 'HBO'), (4, 'YOUTUBE'), (5, 'CDA'), (3, 'AMAZONPRIME')], max_length=9, null=True),
        ),
        migrations.AlterField(
            model_name='movie',
            name='genre',
            field=models.PositiveSmallIntegerField(choices=[(0, 'Inne'), (3, 'Sci-fi'), (2, 'Komedia'), (1, 'Horror')], default=0),
        ),
        migrations.AlterField(
            model_name='movie',
            name='platforms',
            field=multiselectfield.db.fields.MultiSelectField(blank=True, choices=[(2, 'NETFLIX'), (1, 'HBO'), (4, 'YOUTUBE'), (5, 'CDA'), (3, 'AMAZONPRIME')], max_length=9, null=True),
        ),
        migrations.AlterField(
            model_name='serial',
            name='genre',
            field=models.PositiveSmallIntegerField(choices=[(0, 'Inne'), (3, 'Sci-fi'), (2, 'Komedia'), (1, 'Horror')], default=0),
        ),
        migrations.AlterField(
            model_name='serial',
            name='platforms',
            field=multiselectfield.db.fields.MultiSelectField(blank=True, choices=[(2, 'NETFLIX'), (1, 'HBO'), (4, 'YOUTUBE'), (5, 'CDA'), (3, 'AMAZONPRIME')], max_length=9, null=True),
        ),
    ]
