# Generated by Django 3.0.2 on 2021-02-19 10:52

from django.db import migrations, models
import multiselectfield.db.fields


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0031_auto_20201021_1904'),
    ]

    operations = [
        migrations.AlterField(
            model_name='anime',
            name='genre',
            field=models.PositiveSmallIntegerField(choices=[(1, 'Horror'), (0, 'Inne'), (2, 'Komedia'), (3, 'Sci-fi')], default=0),
        ),
        migrations.AlterField(
            model_name='anime',
            name='platforms',
            field=multiselectfield.db.fields.MultiSelectField(blank=True, choices=[(1, 'HBO'), (5, 'CDA'), (2, 'NETFLIX'), (4, 'YOUTUBE'), (3, 'AMAZONPRIME')], max_length=9, null=True),
        ),
        migrations.AlterField(
            model_name='movie',
            name='genre',
            field=models.PositiveSmallIntegerField(choices=[(1, 'Horror'), (0, 'Inne'), (2, 'Komedia'), (3, 'Sci-fi')], default=0),
        ),
        migrations.AlterField(
            model_name='movie',
            name='platforms',
            field=multiselectfield.db.fields.MultiSelectField(blank=True, choices=[(1, 'HBO'), (5, 'CDA'), (2, 'NETFLIX'), (4, 'YOUTUBE'), (3, 'AMAZONPRIME')], max_length=9, null=True),
        ),
        migrations.AlterField(
            model_name='serial',
            name='genre',
            field=models.PositiveSmallIntegerField(choices=[(1, 'Horror'), (0, 'Inne'), (2, 'Komedia'), (3, 'Sci-fi')], default=0),
        ),
        migrations.AlterField(
            model_name='serial',
            name='platforms',
            field=multiselectfield.db.fields.MultiSelectField(blank=True, choices=[(1, 'HBO'), (5, 'CDA'), (2, 'NETFLIX'), (4, 'YOUTUBE'), (3, 'AMAZONPRIME')], max_length=9, null=True),
        ),
    ]
